import type { Metadata } from "next";
import { Geist_Mono, Inter, Orbitron } from "next/font/google";
import Navbar from "@/components/navbar";
import "./globals.css";
import { AuthSessionProvider } from "@/components/sessionprovider";

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: "900",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${orbitron.variable} ${inter.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col bg-background font-sans text-zinc-800">
      <AuthSessionProvider>
        <Navbar />
        <div className="flex flex-1 flex-col">{children}</div>
      </AuthSessionProvider>
      </body>
    </html>
  );
}
